personalWebsite/contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact'),
]

# urlpatterns += [
#     path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
# ]

personalWebsite/personalWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('projects/', include('projects.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalWebsite/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path("", views.project_index, name="project_index"),
    path("<int:pk>/", views.project_detail, name="project_detail"),
]

personalWebsite/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.email
    

personalWebsite/projects/models.py
# Create your models here.
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=50)
    repo_link = models.CharField(max_length=100, default='https://github.com/mfmyip/')
    image = models.FilePathField(path="projects/static/img/")
    def __str__(self):
        return self.title

personalWebsite/contact/forms.py
from django import forms
from html import escape

# class NameForm(forms.Form):
#     your_name = forms.CharField(label='Your name', max_length=100)
#     your_email = forms.EmailField(label='Your Email', max_length=100)
#     message = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.Form):
    your_name = forms.CharField(
        label='Your Name', max_length=100,
        widget = forms.TextInput(attrs={'placeholder':'Please enter your name *'})
    )
    your_email = forms.EmailField(
        label='Your Email', max_length=100,
        widget = forms.TextInput(attrs={'placeholder':'Please enter your email *'})
    )
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

    def clean_your_name(self):
        # uses html escape for sanitation
        data = self.cleaned_data['your_name']
        return escape(data)

personalWebsite/contact/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages

from .models import Contact
from .forms import ContactForm

# Create your views here.

def index(request):
    template_name = 'contact/contact.html'

    me = Contact.objects.get(pk=1) # get first obj in contact
    context = {
        'contact': me
    }
    return render(request, template_name, context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry From: " + form.cleaned_data['your_name']
            body = {
                'name': form.cleaned_data['your_name'],
                'email': form.cleaned_data['your_email'],
                'message': form.cleaned_data['message'],
            }
            message = '\n'.join(body.values())
            try:
                # 'from', ['to']
                send_mail(subject, message, 'murphyyip49@gmail.com', ['murphyyip49@gmail.com'])
                messages.success(request, 'Form submission successful!')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('contact:contact')
        
    form = ContactForm()
    me = Contact.objects.get(pk=1) # get first obj in contact
    context = {
        'contact': me,
        'form': form
    }
    return render(request, 'contact/contact.html', context)

personalWebsite/personalWebsite/views.py
from django.shortcuts import render, get_object_or_404


def index(request):
    template_name = 'personalWebsite/index.html'
    context = {}
    return render(request, template_name, context)

personalWebsite/projects/views.py
from django.shortcuts import render, get_object_or_404
from projects.models import Project

def project_index(request):
    template_name = 'projects/index.html'

    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, template_name, context)

def project_detail(request, pk):
    template_name = 'projects/detail.html'
    project = get_object_or_404(Project, pk=pk)
    context = {
        'project': project
    }
    return render(request, template_name, context)

personalWebsite/contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}  
{% block page_content %}




<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Murphy Yip</h3>
    <nav class="nav nav-masthead justify-content-center">
      <a class="nav-link" href="{% url 'index' %}">Home</a>
      <a class="nav-link" href="{% url 'projects:project_index' %}">Projects</a>
      <a class="nav-link active" href="{% url 'contact:contact' %}">Contact</a>
    </nav>
  </div>
</header>

<h4 class="cover-heading">My Contact Details</h4>
<p class="text-break">
    <b>Email:</b><br>
    {{ contact.email }} <br>
    <b>Phone:</b><br>
    {{ contact.phone }}<br>
</p>
<p>
  Or feel free to write your name, email address and a message below to contact me directly.
</p>

<div class="container-fluid bg-light py-3 rounded mb-3">
    {% comment %} CONTACT FORM {% endcomment %}
    <form method="post" class="contactform">
      {% csrf_token %}
        {{form|crispy}}
          <button class='btn btn-primary' type="submit">Submit</button>          
  </form>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <label  {% if message.tags %} class="{{ message.tags }} justify-content-center" {% endif %}>
        {{ message }} 
      </label>
      {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock %}

personalWebsite/personalWebsite/templates/base.html
{% load static %}
<!-- saved from url=(0049)https://getbootstrap.com/docs/4.0/examples/cover/ -->
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'img/logo.png' %}">

  <title>Cover Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>

<body class="text-center">
  <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

    {% block page_content %}{% endblock %}

    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>This site itself is a side project lowkey</p>
      </div>
    </footer>
  </div>
</body>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.2.1.slim.min.js.download' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js.download' %}"></script>
<script src="{% static 'js/bootstrap.min.js.download' %}"></script>
{% comment %} <script src="./Bootstrap_files/bootstrap.min.js.download"></script> {% endcomment %}
  

personalWebsite/personalWebsite/templates/personalWebsite/index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

<header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Murphy Yip</h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="{% url 'index' %}">Home</a>
        <a class="nav-link" href="{% url 'projects:project_index' %}">Projects</a>
        <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
      </nav>
    </div>
</header>

<div class="container-lg">
    <div class="row">
        <div class="col-md ">
            <h1 class="cover-heading">Hello!</h1>
            <p class="lead">I am a passionate developer. My aim is to utilise my expertise in software development and data science to deliver innovative solutions that drive
                business success. I am passionate about using technology to solve real-world problems and I am eager to bring my
                unique perspective and problem-solving skills to a team that values collaboration and continuous improvement.</p>
            <a href="https://drive.google.com/file/d/1qeiXbe2TTb3pxplTXD6_03JxNAoY4NRG/view?usp=sharing" class="btn btn-lg btn-secondary">My Resume</a>
            <a href="https://github.com/mfmyip" class="btn btn-lg btn-secondary">GitHub</a>
            
        </div>
        <div class="card bg-light mb-3">
            <img src="https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOQSX9meX1LfZKUDdkwFqBYF05PWZr61B9T38mctuJNMCgDSRi7KCW4Q9Sez3SkzCj-E3Q_DbYVCaNxFlMTtBOAT84GUPQ=w1920-h912" class="img-fluid" alt="...">
        </div>
    </div>      
</div>
  
{% endblock %}

personalWebsite/projects/templates/projects/detail.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">{{ project.title }}</h3>
    <nav class="nav nav-masthead justify-content-center">
      <a class="nav-link " href="{% url 'index' %}">Home</a>
      <a class="nav-link active"  href="{% url 'projects:project_index' %}">Projects</a>
      <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
    </nav>
  </div>
</header>

<main role="main" class="cover">
    <div class="row">
    <div class="col-md-6">
        <div class="card bg-light mb-3">
            <img src="{% static project.image %}" alt="" width="100%">
        </div>
    </div>
    <div class="col-md-4">
        <h5 style="text-align:left">About the project:</h5>
        <p style="text-align:left"> {{ project.description }} </p>
        <br>
        <h5 style="text-align:left">Technology used:</h5>
        <p style="text-align:left"> {{ project.technology }} </p>
    </div>
    </div>
</main>

{% endblock %}

personalWebsite/projects/templates/projects/index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Murphy Yip</h3>
    <nav class="nav nav-masthead justify-content-center">
      <a class="nav-link " href="{% url 'index' %}">Home</a>
      <a class="nav-link active"  href="{% url 'projects:project_index' %}">Projects</a>
      <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
    </nav>
  </div>
</header>

<main role="main" class="cover">
  <div class="row ">
      {% for project in projects %}
          <div class="col-md d-flex align-items-stretch">
              <div class="card lg">
                  <img class="card-img-top" src="{% static project.image %}">
                  <div class="card-body d-flex flex-column">
                      <h5 class="cover-head mt-auto">{{ project.title }}</h5>
                      <p class="card-text mt-auto">{{ project.description }}</p>
                      <a href="{{ project.repo_link }}"
                          class="btn btn-primary mt-auto">
                          Github
                      </a>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
</main>

{% endblock %}